import { Router } from "express";
import { alunos, atenderDec, autorizarJustific, cargaHoraria, classes, classificacoesTrimestral, classificarMedia, cursos, eliminarPauta, gerarPauta, matricular, minipautas, outrasOpcoes, pauta, pauta2, pautaPDF, pautas, pedagogicoHome, pedidos, pesquisarMinipautas, relatorioEstatistic, outrOp, solicitacao, solicitacoes, turmas, aproveitamentoTrimestral, aproveitamentoCurso, actualizarAproveitamento, conselhoDeNotas, iniciarConselhoDeNotas, conselhoIndividual, salvarConselhoIndividual, finalizarConseNotas, aplicarConseAutomatico, aprovados, editarPauta, pautaIndividual, salvarPautaIndividual, adicionarAlunoPauta, reabrirConselho, gerarAproveitamento, gerarPautaLocal, deleteNotas, editarNotasFicha, actualizarMedias, actualizarMediasTDAlunos, aplicarPrimeiroConseAutomatico, iniciarConselhoDeNotasComAdmin, vagasDisponiveis } from "../controlles/pedagogico.controll.js";
import { eAdmin, eCoordCurso, eJuriPresidente, veryLogin } from "../../helpers/eAdmin.js";
import { declaracaoSemNota } from "../controlles/relatorios.controll.js";
import { alunosConcluido, alunosNaoMatriculados, coordenacao } from "../controlles/professor.controll.js";
const router = Router()

router.get('/', veryLogin, eAdmin, pedagogicoHome)
router.get('/minipautas', veryLogin, eAdmin, minipautas)
router.post('/gerarPauta',veryLogin, eAdmin, gerarPauta)
router.post('/gerarPautaLocal',veryLogin, eAdmin, gerarPautaLocal)
router.get('/pautas', veryLogin, eAdmin, pautas)
router.get('/pauta/:id', veryLogin, eAdmin, pauta)
router.get('/pauta3/:id', veryLogin, eAdmin, pauta2) // Uma nova tentativa para ordenar as disciplinas
router.post('/pautaPDF', veryLogin, eAdmin, pautaPDF)
router.get('/alunos', veryLogin, eAdmin, alunos)
router.get('/turmas', veryLogin, eAdmin, turmas)
router.get('/classes', veryLogin, eAdmin, classes)
router.get('/cursos', veryLogin, eAdmin, cursos)
router.get('/matricular', veryLogin, eAdmin, matricular)
router.get('/solicitacoes', veryLogin, eAdmin, solicitacoes)
router.get('/cargaHoraria', veryLogin, eAdmin, cargaHoraria)
router.get('/solicitacao/:idSolicitacao', veryLogin, eAdmin, solicitacao)
router.post('/autorizarJustific', veryLogin, eAdmin, autorizarJustific)
router.get('/pedidos', veryLogin, eAdmin, pedidos)
router.post('/atenderDec', veryLogin, eAdmin, atenderDec)
router.post('/declaracaoSemNota', veryLogin, eAdmin, declaracaoSemNota)
router.get('/outrOp', veryLogin, eAdmin, outrOp)
router.get('/relatorioEstatistic', veryLogin, eAdmin, relatorioEstatistic)
router.get('/relatorioEstatisticII', veryLogin, eAdmin)
router.get('/aproveitamentoTrimestral/:trimestre', veryLogin, eAdmin, aproveitamentoTrimestral)
router.post('/aproveitamentoCursos', veryLogin, eAdmin, aproveitamentoCurso)
router.post('/actualizarAproveitamento', veryLogin, eAdmin, actualizarAproveitamento)
router.post('/gerarAproveitamento', veryLogin, eAdmin, gerarAproveitamento)
router.post('/eliminarPauta', veryLogin, eAdmin, eliminarPauta)
router.get('/outrasOpcoes', veryLogin, eAdmin, outrasOpcoes)
router.get('/classificacoesTrimestral', veryLogin, eAdmin, classificacoesTrimestral)
router.post('/classificarMedia', veryLogin, eAdmin, classificarMedia)
router.post('/pesquisarMinipautas', veryLogin, eAdmin, pesquisarMinipautas)
router.get('/conselhoDeNotas/:id', veryLogin, eJuriPresidente, conselhoDeNotas) // Conselho de notas
router.post('/iniciarConselho', veryLogin, eJuriPresidente, iniciarConselhoDeNotas)
router.post('/iniciarConselhoComAdmin', veryLogin, eAdmin, iniciarConselhoDeNotasComAdmin)
router.post('/conselhoIndividual', veryLogin, eJuriPresidente, conselhoIndividual) 
router.post('/salvarConselhoIndividual', veryLogin, eJuriPresidente, salvarConselhoIndividual) 
router.post('/finalizarConseNotas', veryLogin, eJuriPresidente, finalizarConseNotas) 
router.post('/reabrirConselho', veryLogin, eAdmin, reabrirConselho) 
router.post('/aplicarPrimeiroConseAutomatico', veryLogin, aplicarPrimeiroConseAutomatico) 
router.post('/aplicarConseAutomatico', veryLogin, aplicarConseAutomatico) 
router.get('/aprovados/:id', veryLogin, aprovados) 
router.get('/editarPauta/:id', veryLogin, editarPauta) 
router.post('/pautaIndividual', veryLogin, pautaIndividual) 
router.post('/salvarPautaIndividual', veryLogin, salvarPautaIndividual) 
router.post('/adicionarAlunoPauta', veryLogin, adicionarAlunoPauta) 
router.get("/coordenacao/:id", veryLogin, eCoordCurso, coordenacao)
router.get("/alunosConcluido/", veryLogin, eAdmin, alunosConcluido)
router.get("/alunosNaoMatriculados/", veryLogin, eAdmin, alunosNaoMatriculados)
router.post("/deleteNotas", veryLogin, eAdmin, deleteNotas)
router.get("/editarNotas/:id", veryLogin, eAdmin, editarNotasFicha)
router.get("/actualizarMedias/:id", veryLogin, actualizarMedias)
router.get("/actualizarMediasTDAlunos/:id", veryLogin, actualizarMediasTDAlunos)
router.get("/vagasDisponiveis", veryLogin, vagasDisponiveis)

//router.get('/professores', professores)

export default router